version: '3.8'

services:
  postgres:
    image: postgres:17.5
    container_name: openschool-postgres
    environment:
      POSTGRES_DB: openschool
      POSTGRES_USER: openschool_user
      POSTGRES_PASSWORD: openschool_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - openschool-network

# OpenSchool Backend Service docker-compose requirements
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: openschool-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - openschool-network

volumes:
  postgres_data:

networks:
  openschool-network:
    driver: bridge